title: "Candibod"
email: candibod@skiff.com
baseUrl: /
timezone: UTC
permalink: "/:title"
logo: "https://candibod-blog.s3.amazonaws.com/icon/icon-black-120.png"
favicon: "https://candibod-blog.s3.amazonaws.com/icon/favicon-black.ico"
default_blog_image: "https://candibod-blog.s3.amazonaws.com/assets/default.jpg"
author: Jeevan
paginate: 10
locale: en_us
lang: en_us
feed_items: 4
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  jeevan:
    name: Jeevan
    display_name: Jeevan
    avatar: "assets/images/Jeevan.png"
    email: candibod@skiff.com
    web: https://candibod.in
    description: "Personal blog"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
